---
# Based on https://github.com/koalaman/shellcheck/wiki/GitHub-Actions
name: Differential ShellCheck
"on":
  pull_request:
    types: [opened, reopened, synchronize]
    paths: [bin/p3wm]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      pull-requests: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
